### ISSUE TITLE
shooting while aiming fov bug

### ISSUE THREAD

**Issue by hartycleric** [relaxtakenotes/enhanced-hl2-weapons#2] opened 2023-10-23 13:13 UTC
when i shoot while zoomed in my fov switches back to the non zoomed fov when i'm shooting

**Comment by relaxtakenotes** [comment] 2023-10-23 14:04
duplicate of https://github.com/relaxtakenotes/enhanced-hl2-weapons/issues/1

**Closed by relaxtakenotes** 2023-10-23 14:04 UTC
